name: "Check"

on:
  workflow_dispatch:
  push:

defaults:
  run:
    working-directory: ./zellij

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.82.0
        with:
          components: rustfmt, clippy
          targets: wasm32-wasip1

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy -- -D warnings
